version: '3'
services:
  employee:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8300
        - URL_REPO=http://192.168.2.177:8080/mcfrank/employee
    environment:
      - PORT=8300
      - URL_REPO=http://192.168.2.177:8080/mcfrank/employee
    networks:
      - mycelium
networks:
  mycelium:
    driver: bridge
